Feature/velodyne
CIT-Autonomous-Robot-Lab/raspicat_ros pull request #5
Opened 2022-06-15 11:53 UTC by TonoLeo

・velodyneを追加

2022-06-15 12:22 UTC, uhobeike requested changes

2022-06-15 12:22 UTC, uhobeike commented on raspicat_bringup/launch/raspicat_bringup.launch
> +  <arg name="velodyne"    default="false"/>
`vlp16`が良いかな

2022-06-15 12:22 UTC, uhobeike commented on raspicat_bringup/launch/raspicat_bringup.launch
> +  <include if="$(arg velodyne)" file="$(find velodyne_pointcloud)/launch/VLP16_points.launch">
ここも

2022-06-15 12:22 UTC, uhobeike commented on raspicat_bringup/launch/raspicat_bringup.launch
> +    <arg name="frame_id" value="urg_lrf_link" />
ここは、こんな感じにしてほしい
https://github.com/CIT-Autonomous-Robot-Lab/raspicat_ros/blob/a714db322387ac9d83e70d264795dc8ec78c0076/raspicat_bringup/launch/raspicat_bringup.launch#L34

2022-06-15 14:17 UTC, uhobeike requested changes

2022-06-15 14:17 UTC, uhobeike commented on raspicat_bringup/launch/raspicat_bringup.launch
> +    <param name="frame_id"              value="$(arg lidar_frame_id)"/>
すまん。
これは引数なので`param`ではなくて`arg`だった。
https://github.com/ros-drivers/velodyne/blob/f4c35a252394b0da6177ee0fe94b4c9f2c038da9/velodyne_pointcloud/launch/VLP16_points.launch#L9

2022-06-15 14:28 UTC, TonoLeo commented on raspicat_bringup/launch/raspicat_bringup.launch
> +    <param name="frame_id"              value="$(arg lidar_frame_id)"/>
了解です、修正します

2022-06-16 01:21 UTC, uhobeike requested changes
多分これで最後です。
修正よろしくお願いします。

2022-06-16 01:21 UTC, uhobeike commented on raspicat_bringup/launch/raspicat_bringup.launch
> +
超細かいけど、この行いらないです。

2022-06-16 01:22 UTC, uhobeike commented on raspicat_bringup/launch/raspicat_bringup.launch
> +
あれ、また指定できてないな。。。。
51行目がいらないです。

2022-06-16 01:38 UTC, uhobeike approved these changes
大丈夫そう

2022-06-16 01:40 UTC, merged